### ISSUE TITLE
rust-openssl in td-client-rust can get panicked depending on environment (was "materialized view crashes database")

### ISSUE THREAD

**Issue by rotten** [komamitsu/treasuredata_fdw#23]
Running on Ubuntu 17.04 with PostgresSQL 9.6.3 (on my laptop), I have installed the latest treasure_data FDW - version 1.2.0 with Rust 1.16.0

I put the database in debug5.

When I go to create a materialized view it crashes the database with:

```
    PL/pgSQL function treasure_data."createWebResponsePartition"(character varying,character varying) line 4 at EXECUTE
2017-07-06 15:10:15.551 EDT clarivoy [local] rick STATEMENT:  select treasure_data."createWebResponsePartition"('2017'::varchar, '03'::varchar);
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
2017-07-06 15:10:15.638 EDT    DEBUG:  reaping dead processes
2017-07-06 15:10:15.638 EDT    DEBUG:  server process (PID 16035) was terminated by signal 6: Aborted
2017-07-06 15:10:15.638 EDT    DETAIL:  Failed process was running: select treasure_data."createWebResponsePartition"('2017'::varchar, '03'::varchar);
2017-07-06 15:10:15.638 EDT    LOG:  server process (PID 16035) was terminated by signal 6: Aborted
2017-07-06 15:10:15.638 EDT    DETAIL:  Failed process was running: select treasure_data."createWebResponsePartition"('2017'::varchar, '03'::varchar);
2017-07-06 15:10:15.638 EDT    LOG:  terminating any other active server processes

```

I just noticed in the client that it doesn't like the "to_timestamp" function in the where clause:
`DEBUG:  This function doesn't work on Treasure Data: to_timestamp
`

Maybe that is what is crashing it.  I'll do more experiments later this evening.  Meanwhile I wanted to log the issue.  I wouldn't have expected that to take down the whole database, even if it was an unsupported function.

**Comment by rotten** [comment]
Actually, this select crashes my database:
select * from treasure_data.web_responses_ft where to_timestamp(time) > '2017-06-01' limit 10;

Where "web_responses_ft" is my foreign table.

**Comment by rotten** [comment]
Actually this crashes the database too, something else must be wrong:
clarivoy=# select * from treasure_data.web_responses_ft limit 10;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

**Comment by rotten** [comment]
I tried switching the query engine from 'presto' to 'hive'.  That didn't change anything.

**Comment by komamitsu** [comment]
@rotten Thanks for reporting this issue and sorry for the trouble.

It looks the root cause of this issue is `limit` clause. With it, I can reproduce this issue. I'll look into it.

**Comment by komamitsu** [comment]
A workaround is adding `order by` to the query which uses `limit` if possible.

**Comment by komamitsu** [comment]
I found the cause.

With `limit` clause w/o `order by`, PostgresSQL's foreign data wrappers don't consume all result rows and finishes right away when fetches the specified number of result rows.

In treasuredata_fdw, a spawned thread fetches result rows from Treasure Data and puts them into an in-memory queue in background. But if a query has `limit` w/o `order by`, resources in Postgres allocated for the query are released quickly even while the thread is processing. In this case, the thread can't continue processing and calls `elog(ERROR)` which aborts the query. But the query is already finished, so it crashes.
 
When I commented out these lines, the crash isn't reproduced.
https://github.com/komamitsu/treasuredata_fdw/blob/master/bridge_td_client_rust/src/lib.rs#L210-L212

I'll fix this issue with adding a test for it later.

**Comment by rotten** [comment]
Interesting, thanks for discovering the root cause so quickly!  I look forward to the fix.

**Comment by komamitsu** [comment]
@rotten I fixed this issue in https://github.com/komamitsu/treasuredata_fdw/pull/24 and merged the change into `master` branch.

Can you confirm this issue isn't reproduced with the current `master` branch with your environment? If it works, I'll release a new version. Thanks in advance.

**Comment by rotten** [comment]
I should have some time tomorrow (Sunday) morning, to test it.  I'll let you know.

**Comment by rotten** [comment]
I pulled the updated code from master.  Ran make, then sudo make install.
I restarted postgresql.
I ran alter extension treasuredata_fdw update.
I dropped the server and foreign table and recreated them.
I even added an 'order by' clause.

It still crashes on me.
:-(

**Comment by komamitsu** [comment]
@rotten 
I see... Could you tell me how many rows the table has?
Also, could you try `make clean` first?

Without the fix, PostgreSQL crashed in CI test https://travis-ci.org/komamitsu/treasuredata_fdw/builds/251448675.
But the current `master` branch works fine with the test...https://travis-ci.org/komamitsu/treasuredata_fdw/builds/251483262

**Comment by rotten** [comment]
There are 230M rows in the Treasure Data table.   I don't think the query gets that far though.  It crashes immediately.  I never see a job in the jobs queue in the Treasure Data console.

I tried make clean... and then the rest of the steps above and we are still crashing.

```
2017-07-10 11:59:47.726 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-10 11:59:47.727 EDT mydb [local] rick LOG:  connection authorized: user=rick database=mydb
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
2017-07-10 11:59:54.338 EDT    LOG:  server process (PID 21036) was terminated by signal 6: Aborted
2017-07-10 11:59:54.338 EDT    DETAIL:  Failed process was running: select * from treasure_data.my_foreign_table limit 10
	;
2017-07-10 11:59:54.338 EDT    LOG:  terminating any other active server processes
2017-07-10 11:59:54.339 EDT    WARNING:  terminating connection because of crash of another server process
2017-07-10 11:59:54.339 EDT    DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-07-10 11:59:54.339 EDT    HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-07-10 11:59:54.340 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-10 11:59:54.340 EDT mydb [local] rick FATAL:  the database system is in recovery mode
2017-07-10 11:59:54.341 EDT    LOG:  all server processes terminated; reinitializing
2017-07-10 11:59:54.360 EDT    LOG:  database system was interrupted; last known up at 2017-07-10 11:58:01 EDT
2017-07-10 11:59:59.778 EDT    LOG:  database system was not properly shut down; automatic recovery in progress
2017-07-10 11:59:59.792 EDT    LOG:  redo starts at 25/82006F98
2017-07-10 11:59:59.793 EDT    LOG:  invalid record length at 25/820252B0: wanted 24, got 0
2017-07-10 11:59:59.793 EDT    LOG:  redo done at 25/82025288
2017-07-10 11:59:59.793 EDT    LOG:  last completed transaction was at log time 2017-07-10 11:59:46.643443-04
2017-07-10 11:59:59.933 EDT    LOG:  MultiXact member wraparound protections are now enabled
2017-07-10 11:59:59.938 EDT    LOG:  autovacuum launcher started
2017-07-10 11:59:59.938 EDT    LOG:  database system is ready to accept connections
```

**Comment by rotten** [comment]
How do I do a "Run with RUST_BACKTRACE=1" ?

**Comment by komamitsu** [comment]
> It crashes immediately. I never see a job in the jobs queue in the Treasure Data console.

Oh, weird...

I think with RUST_BACKTRACE=1 Rust outputs a backtrace to STDOUT or STDERR. So it won't appear on PostgreSQL log.

I have some questions.
1. Is the crash still reproduced with `select * from treasure_data.web_responses_ft limit 10`?
2. How about removing `LIMIT` clause?
3. Could you give me the definition of the table **masking your API key**?

**Comment by rotten** [comment]
1) Yes.
2) Yes - still crashes.

3)
```
CREATE SERVER treasuredata_server FOREIGN DATA WRAPPER treasuredata_fdw;
grant usage on foreign server treasuredata_server to some_role;
```

Column names changed to protect the innocent:

```
`\i ~/td_auth.sql

drop foreign table if exists treasure_data.web_responses_ft cascade;

create foreign table treasure_data.web_responses_ft (

    time                     integer,
    another_time             integer,
    some_id                  varchar,
    some_other_id            varchar,
    yet_another_id           varchar,
    and_some_other_id        integer,
    and_some_other_metadata  varchar,
    something_id             integer,
    something_metadata       varchar,
    some_url                 varchar,
    some_other_url           varchar, 
    interesting_data         varchar,
    other_interesting_data   varchar,
    details_data             varchar, 
    supplemental_data        varchar,
    illuminating_data        varchar, 
    some_set_of_data         varchar[],
    some_true_false_thing    boolean,
    really_detailed_data     varchar,
    sparse_data              varchar, 
    cryptic_data             varchar,  
    set_of_other_stuff       varchar[],
    set_of_md5_hashes        varchar[],
    less_useful_data         varchar,
    trivial_data             varchar,     
    more_trivial_data        varchar

)

  server treasuredata_server options (
    apikey     :td_api_key,
    database     'hits',
    --query_engine 'presto',
    query_engine 'hive',
    table                web_responses'
)
;

grant select on treasure_data.web_responses_ft to some_role;

```

**Comment by komamitsu** [comment]
@rotten Thanks.

Unfortunately, I can't reproduce it with the table definition... (`table  web_responses'` is typo of `table  'web_responses'`, right?)

Can I ask you to try the followings? Thanks in advance.

1. I created a branch https://github.com/komamitsu/treasuredata_fdw/tree/investigate-issue-23 that has some additional logging. Can you try this branch like this and show me log messages?

```
$ git fetch origin
$ git checkout investigate-issue-23
```

2. Does treasuredata_fdw work with this Treasure Data table in your environment? `sample_datasets` database is shared one.

```
CREATE FOREIGN TABLE sample_www_access (
    time integer,
    host varchar,
    path varchar,
    referer varchar,
    code integer,
    agent varchar,
    size integer,
    method varchar
)
SERVER treasuredata_server OPTIONS (
    apikey 'your_api_key',
    database 'sample_datasets',
    query_engine 'presto',
    table 'www_access'
);
```

**Comment by rotten** [comment]
I'm sorry, I got pulled in another direction for a few days.  I'll try to get back to this today.

**Comment by rotten** [comment]
After pulling and installing this branch, no, the sample table doesn't work either.
```
mydb=# \dE
                 List of relations
 Schema |       Name        |     Type      | Owner 
--------+-------------------+---------------+-------
 public | sample_www_access | foreign table | rick
(1 row)

mydb=# select * from public.sample_www_access;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 

```

**Comment by rotten** [comment]
I do get this error in the logs:
`thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
`

**Comment by komamitsu** [comment]
@rotten Was there any debug log? I added some additional logging (DEBUG1) in the branch.

**Comment by rotten** [comment]
Oops - I didn't have the database in debug mode.  I bumped it to debug5.
Here is what I see when I run the select:

```
# select * from public.sample_www_access;
DEBUG:  StartTransactionCommand
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children: 
DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
DEBUG:  issueQuery >>>> apikey:xxx, endpoint:(null), query_engine:presto, database:sample_datasets, query:SELECT "time", host, path, referer, code, agent, size, method FROM www_access
DEBUG:  issue_query: >>>> Converting apikey
DEBUG:  issue_query: >>>> Converting endpoint
DEBUG:  issue_query: >>>> Converting query_engine
DEBUG:  issue_query: >>>> Converting database
DEBUG:  issue_query: >>>> Converting query
DEBUG:  issue_query: >>>> Creating domain_key
DEBUG:  issue_query: entering
DEBUG:  issue_query: apikey.len=45
DEBUG:  issue_query: endpoint=None
DEBUG:  issue_query: query_engine="presto"
DEBUG:  issue_query: database="sample_datasets"
DEBUG:  issue_query: query="SELECT \"time\", host, path, referer, code, agent, size, method FROM www_access"
DEBUG:  issue_query: domain_key=Uuid("xxx")
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```

And here are the logs:

```
2017-07-20 10:08:58.426 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-20 10:08:58.427 EDT mydb [local] rick LOG:  connection authorized: user=rick database=mydb
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
2017-07-20 10:09:01.720 EDT    LOG:  server process (PID 22178) was terminated by signal 6: Aborted
2017-07-20 10:09:01.720 EDT    DETAIL:  Failed process was running: select * from public.sample_www_access;
2017-07-20 10:09:01.720 EDT    LOG:  terminating any other active server processes
2017-07-20 10:09:01.721 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-20 10:09:01.721 EDT mydb [local] rick FATAL:  the database system is in recovery mode
2017-07-20 10:09:01.721 EDT    WARNING:  terminating connection because of crash of another server process
2017-07-20 10:09:01.721 EDT    DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-07-20 10:09:01.721 EDT    HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-07-20 10:09:01.723 EDT    LOG:  all server processes terminated; reinitializing
2017-07-20 10:09:01.730 EDT    LOG:  database system was interrupted; last known up at 2017-07-20 10:08:53 EDT
2017-07-20 10:09:07.223 EDT    LOG:  database system was not properly shut down; automatic recovery in progress
2017-07-20 10:09:07.244 EDT    LOG:  invalid record length at 25/82080720: wanted 24, got 0
2017-07-20 10:09:07.244 EDT    LOG:  redo is not required
2017-07-20 10:09:07.293 EDT    LOG:  MultiXact member wraparound protections are now enabled
2017-07-20 10:09:07.297 EDT    LOG:  autovacuum launcher started
2017-07-20 10:09:07.298 EDT    LOG:  database system is ready to accept connections
2017-07-20 10:09:10.922 EDT    LOG:  received fast shutdown request
2017-07-20 10:09:10.922 EDT    LOG:  aborting any active transactions
2017-07-20 10:09:10.922 EDT    LOG:  autovacuum launcher shutting down
2017-07-20 10:09:10.926 EDT    LOG:  shutting down
2017-07-20 10:09:10.954 EDT    LOG:  database system is shut down

```

**Comment by komamitsu** [comment]
@rotten Thank you for the information. It seems a possible cause is either SSL related library or handling a query engine type string "presto".

Can I ask you to check the followings?

1. Did you already install `libssl-dev` to your Ubuntu 17.04? If not, could you try again after installing it?

2.  I added one more log message to the branch `investigate-issue-23`. Could you `git pull origin investigate-issue-23` and test with it again?

3. How about trying with `postgres` role?

**Comment by rotten** [comment]
libssl-dev was installed:

```
rotten@rick-laptop rotten/src/treasuredata_fdw $  dpkg -l | grep ssl-dev
ii  libssl-dev:amd64                                1.0.2g-1ubuntu11.2                          amd64        Secure Sockets Layer toolkit - development files
rotten@rick-laptop rotten/src/treasuredata_fdw $  
```

I did a pull, make clean, sudo make install, and pg_ctl stop, pg_ctl start

Same error:

```
mydb=# select * from public.sample_www_access;
DEBUG:  StartTransactionCommand
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children: 
DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
DEBUG:  issueQuery >>>> apikey:xxx, endpoint:(null), query_engine:presto, database:sample_datasets, query:SELECT "time", host, path, referer, code, agent, size, method FROM www_access
DEBUG:  issue_query: >>>> Converting apikey
DEBUG:  issue_query: >>>> Converting endpoint
DEBUG:  issue_query: >>>> Converting query_engine
DEBUG:  issue_query: >>>> Converting database
DEBUG:  issue_query: >>>> Converting query
DEBUG:  issue_query: >>>> Creating domain_key
DEBUG:  issue_query: entering
DEBUG:  issue_query: apikey.len=45
DEBUG:  issue_query: endpoint=None
DEBUG:  issue_query: query_engine="presto"
DEBUG:  issue_query: database="sample_datasets"
DEBUG:  issue_query: query="SELECT \"time\", host, path, referer, code, agent, size, method FROM www_access"
```
DEBUG:  issue_query: domain_key=Uuid("xxx")
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> ^D\q

Log file:

```
2017-07-21 06:40:27.687 EDT    LOG:  database system was shut down at 2017-07-21 06:37:33 EDT
2017-07-21 06:40:27.691 EDT    LOG:  MultiXact member wraparound protections are now enabled
2017-07-21 06:40:27.693 EDT    LOG:  autovacuum launcher started
2017-07-21 06:40:27.693 EDT    LOG:  database system is ready to accept connections
2017-07-21 06:40:31.355 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-21 06:40:31.355 EDT mydb [local] rick LOG:  connection authorized: user=rick database=mydb
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
2017-07-21 06:40:35.017 EDT    LOG:  server process (PID 4578) was terminated by signal 6: Aborted
2017-07-21 06:40:35.017 EDT    DETAIL:  Failed process was running: select * from public.sample_www_access;
2017-07-21 06:40:35.017 EDT    LOG:  terminating any other active server processes
2017-07-21 06:40:35.017 EDT    WARNING:  terminating connection because of crash of another server process
2017-07-21 06:40:35.017 EDT    DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-07-21 06:40:35.017 EDT    HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-07-21 06:40:35.018 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-21 06:40:35.018 EDT mydb [local] rick FATAL:  the database system is in recovery mode
2017-07-21 06:40:35.019 EDT    LOG:  all server processes terminated; reinitializing
2017-07-21 06:40:35.026 EDT    LOG:  database system was interrupted; last known up at 2017-07-21 06:40:27 EDT
2017-07-21 06:40:40.488 EDT    LOG:  database system was not properly shut down; automatic recovery in progress
2017-07-21 06:40:40.500 EDT    LOG:  invalid record length at 25/82080A30: wanted 24, got 0
2017-07-21 06:40:40.500 EDT    LOG:  redo is not required
2017-07-21 06:40:40.549 EDT    LOG:  MultiXact member wraparound protections are now enabled
2017-07-21 06:40:40.552 EDT    LOG:  database system is ready to accept connections
2017-07-21 06:40:40.552 EDT    LOG:  autovacuum launcher started
```

I don't actually have a postgres role on this database.
The "rick" user does have super though:

```
mydb=# \du rick
DEBUG:  StartTransactionCommand
DEBUG:  StartTransaction
DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children: 
DEBUG:  CommitTransactionCommand
DEBUG:  CommitTransaction
DEBUG:  name: unnamed; blockState:       STARTED; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children: 
LOG:  duration: 2.713 ms  statement: SELECT r.rolname, r.rolsuper, r.rolinherit,
  r.rolcreaterole, r.rolcreatedb, r.rolcanlogin,
  r.rolconnlimit, r.rolvaliduntil,
  ARRAY(SELECT b.rolname
        FROM pg_catalog.pg_auth_members m
        JOIN pg_catalog.pg_roles b ON (m.roleid = b.oid)
        WHERE m.member = r.oid) as memberof
, r.rolreplication
, r.rolbypassrls
FROM pg_catalog.pg_roles r
WHERE r.rolname ~ '^(rick)$'
ORDER BY 1;
                                   List of roles
 Role name |                         Attributes                         | Member of 
-----------+------------------------------------------------------------+-----------
 rick      | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

mydb=# 
```

**Comment by rotten** [comment]
I just realized that I only had turned on debug5 for the client.  I still had log_min_messages and log_min_error_statement to set too.  I turned those on and ran the query again:

```
2017-07-21 11:12:49.826 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.826 EDT mydb [local] rick DEBUG:  StartTransaction
2017-07-21 11:12:49.826 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.826 EDT mydb [local] rick DEBUG:  name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children: 
2017-07-21 11:12:49.826 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issueQuery >>>> apikey:xxx, endpoint:(null), query_engine:presto, database:sample_datasets, query:SELECT "time", host, path, referer, code, agent, size, method FROM www_access
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting apikey
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting endpoint
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting query_engine
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting database
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting query
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: >>>> Creating domain_key
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: entering
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: apikey.len=45
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: endpoint=None
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: query_engine="presto"
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: database="sample_datasets"
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: query="SELECT \"time\", host, path, referer, code, agent, size, method FROM www_access"
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-21 11:12:49.828 EDT mydb [local] rick DEBUG:  issue_query: domain_key=Uuid("xxx")
2017-07-21 11:12:49.828 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
2017-07-21 11:12:49.944 EDT    DEBUG:  reaping dead processes
2017-07-21 11:12:49.944 EDT    DEBUG:  server process (PID 14619) was terminated by signal 6: Aborted
2017-07-21 11:12:49.944 EDT    DETAIL:  Failed process was running: select * from public.sample_www_access;
2017-07-21 11:12:49.944 EDT    LOG:  server process (PID 14619) was terminated by signal 6: Aborted
2017-07-21 11:12:49.944 EDT    DETAIL:  Failed process was running: select * from public.sample_www_access;
2017-07-21 11:12:49.944 EDT    LOG:  terminating any other active server processes
2017-07-21 11:12:49.944 EDT    DEBUG:  sending SIGQUIT to process 14609
2017-07-21 11:12:49.944 EDT    DEBUG:  sending SIGQUIT to process 14608
2017-07-21 11:12:49.944 EDT    DEBUG:  sending SIGQUIT to process 14610
2017-07-21 11:12:49.944 EDT    DEBUG:  sending SIGQUIT to process 14611
2017-07-21 11:12:49.944 EDT    DEBUG:  sending SIGQUIT to process 14612
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  proc_exit(-1): 0 callbacks to make
2017-07-21 11:12:49.944 EDT    WARNING:  terminating connection because of crash of another server process
2017-07-21 11:12:49.944 EDT    DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-07-21 11:12:49.944 EDT    HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  proc_exit(-1): 0 callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  proc_exit(-1): 0 callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  proc_exit(-1): 0 callbacks to make
2017-07-21 11:12:49.944 EDT    DEBUG:  forked new backend, pid=14621 socket=9
2017-07-21 11:12:49.945 EDT    DEBUG:  writing stats file "pg_stat/global.stat"
2017-07-21 11:12:49.945 EDT    DEBUG:  writing stats file "pg_stat/db_16557.stat"
2017-07-21 11:12:49.945 EDT    DEBUG:  removing temporary stats file "pg_stat_tmp/db_16557.stat"
2017-07-21 11:12:49.945 EDT    DEBUG:  writing stats file "pg_stat/db_0.stat"
2017-07-21 11:12:49.945 EDT    DEBUG:  removing temporary stats file "pg_stat_tmp/db_0.stat"
2017-07-21 11:12:49.945 EDT    DEBUG:  reaping dead processes
2017-07-21 11:12:49.945 EDT    DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
2017-07-21 11:12:49.945 EDT    DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
2017-07-21 11:12:49.945 EDT    DEBUG:  proc_exit(-1): 0 callbacks to make
2017-07-21 11:12:49.945 EDT    DEBUG:  reaping dead processes
2017-07-21 11:12:49.945 EDT    DEBUG:  reaping dead processes
2017-07-21 11:12:49.945 EDT    DEBUG:  reaping dead processes
2017-07-21 11:12:49.945 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-21 11:12:49.945 EDT mydb [local] rick FATAL:  the database system is in recovery mode

```

**Comment by komamitsu** [comment]
@rotten Thanks! According to your log, the root cause seems to be isolated to SSL/TLS functions.

But in the current implementation, a SSL error isn't captured in PostgreSQL foreign table framework. So I made additional changes to https://github.com/komamitsu/treasuredata_fdw/tree/investigate-issue-23 so that we can get detailed error information.

Could I ask you to try these two things? Thanks a lot in advance.

1. With the latest https://github.com/komamitsu/treasuredata_fdw/tree/investigate-issue-23 and DEBUG1, issue a query and get debug/error logs masking sensitive values

2. Execute the following commands

```
$ pg_config --configure
$ pg_config --ldflags
$ pg_config --cflags
$ ldd $(pg_config --bindir)/postgres
```

**Comment by rotten** [comment]
Query:

```
mydb=# select * from public.sample_www_access;
DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
DEBUG:  issueQuery >>>> apikey:xxx, endpoint:(null), query_engine:presto, database:sample_datasets, query:SELECT "time", host, path, referer, code, agent, size, method FROM www_access
DEBUG:  issue_query: >>>> Converting apikey
DEBUG:  issue_query: >>>> Converting endpoint
DEBUG:  issue_query: >>>> Converting query_engine
DEBUG:  issue_query: >>>> Converting database
DEBUG:  issue_query: >>>> Converting query
DEBUG:  issue_query: >>>> Creating domain_key
DEBUG:  issue_query: entering
DEBUG:  issue_query: apikey.len=45
DEBUG:  issue_query: endpoint=None
DEBUG:  issue_query: query_engine="presto"
DEBUG:  issue_query: database="sample_datasets"
DEBUG:  issue_query: query="SELECT \"time\", host, path, referer, code, agent, size, method FROM www_access"
DEBUG:  issue_query: domain_key=Uuid("xxx")
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> ^D\q
```

logs:
```
2017-07-24 12:17:30.792 EDT    LOG:  database system is ready to accept connections
2017-07-24 12:17:37.402 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-24 12:17:37.403 EDT mydb [local] rick LOG:  connection authorized: user=rick database=mydb
2017-07-24 12:17:39.235 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
2017-07-24 12:17:39.235 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.235 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, import_file_size=134217728, atomic_import=0
2017-07-24 12:17:39.235 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.235 EDT mydb [local] rick DEBUG:  issueQuery >>>> apikey:xxx, endpoint:(null), query_engine:presto, database:sample_datasets, query:SELECT "time", host, path, referer, code, agent, size, method FROM www_access
2017-07-24 12:17:39.235 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.235 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting apikey
2017-07-24 12:17:39.235 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.235 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting endpoint
2017-07-24 12:17:39.235 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting query_engine
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting database
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: >>>> Converting query
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: >>>> Creating domain_key
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: entering
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: apikey.len=45
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: endpoint=None
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: query_engine="presto"
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: database="sample_datasets"
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: query="SELECT \"time\", host, path, referer, code, agent, size, method FROM www_access"
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-24 12:17:39.236 EDT mydb [local] rick DEBUG:  issue_query: domain_key=Uuid("xxx")
2017-07-24 12:17:39.236 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
fatal runtime error: failed to initiate panic, error 5
2017-07-24 12:17:39.324 EDT    LOG:  server process (PID 23582) was terminated by signal 6: Aborted
2017-07-24 12:17:39.324 EDT    DETAIL:  Failed process was running: select * from public.sample_www_access;
2017-07-24 12:17:39.324 EDT    LOG:  terminating any other active server processes
2017-07-24 12:17:39.324 EDT    WARNING:  terminating connection because of crash of another server process
2017-07-24 12:17:39.324 EDT    DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-07-24 12:17:39.324 EDT    HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-07-24 12:17:39.325 EDT [unknown] [local] [unknown] LOG:  connection received: host=[local]
2017-07-24 12:17:39.325 EDT mydb [local] rick FATAL:  the database system is in recovery mode
2017-07-24 12:17:39.326 EDT    LOG:  all server processes terminated; reinitializing
```

requested commands:

```
$  pg_config --configure
'--with-tcl' '--with-perl' '--with-python' '--with-pam' '--with-openssl' '--with-libxml' '--with-libxslt' '--with-tclconfig=/usr/lib/x86_64-linux-gnu/tcl8.6' '--with-includes=/usr/include/tcl8.6' 'PYTHON=/usr/bin/python' '--mandir=/usr/share/postgresql/9.6/man' '--docdir=/usr/share/doc/postgresql-doc-9.6' '--sysconfdir=/etc/postgresql-common' '--datarootdir=/usr/share/' '--datadir=/usr/share/postgresql/9.6' '--bindir=/usr/lib/postgresql/9.6/bin' '--libdir=/usr/lib/x86_64-linux-gnu/' '--libexecdir=/usr/lib/postgresql/' '--includedir=/usr/include/postgresql/' '--enable-nls' '--enable-integer-datetimes' '--enable-thread-safety' '--enable-tap-tests' '--enable-debug' '--disable-rpath' '--with-uuid=e2fs' '--with-gnu-ld' '--with-pgport=5432' '--with-system-tzdata=/usr/share/zoneinfo' '--with-systemd' 'CFLAGS=-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5' '--with-krb5' '--with-gssapi' '--with-ldap' '--with-selinux' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2'

$  pg_config --ldflags
-L../../src/common -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -L/usr/lib/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,--as-needed

$  pg_config --cflags
-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/mit-krb5 -fPIC -pie -fno-omit-frame-pointer

$  ldd $(pg_config --bindir)/postgres
	linux-vdso.so.1 =>  (0x00007ffc6bb58000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f576818d000)
	libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 (0x00007f5767f7f000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f5767d16000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f57678d2000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f5767686000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f576747e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f576727a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5766f71000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f5766d1f000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f5766c97000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f57668ce000)
	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007f5766526000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f576630a000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f57660e4000)
	libaudit.so.1 => /lib/x86_64-linux-gnu/libaudit.so.1 (0x00007f5765ebc000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f5765be7000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f57659b3000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f57657af000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f57655a4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5765386000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c34e881000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f5765178000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f5764f5d000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f5764d40000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f5764afe000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f576479e000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f5764576000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f576435e000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f576404f000)
	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007f57625d0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5762248000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5762031000)
	libcap-ng.so.0 => /lib/x86_64-linux-gnu/libcap-ng.so.0 (0x00007f5761e2c000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f5761c28000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f5761a1d000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f5761790000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f57614ed000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f57612b6000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f57610a0000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f5760e3b000)
	libidn.so.11 => /lib/x86_64-linux-gnu/libidn.so.11 (0x00007f5760c06000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f57609f3000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f57607bd000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f576053d000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f576030a000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f5760097000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f575fe81000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f575fc58000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f575fa49000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f575f7fe000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f575f4f7000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f575f2bf000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f575f0b5000)

```

**Comment by komamitsu** [comment]
@rotten Thank you again.

According to your log, it looks the exception actually occurred deeper in a SSL library than I expected. It seems it would take more time to find which code throws the exception since I can't reproduce this issue.

I remember you could use treasuredata_fdw 1.0.0. I upgraded the version of a SSL library after 1.0.0 and I suspect it introduced something wrong with your environment. So I created a new branch https://github.com/komamitsu/treasuredata_fdw/tree/with-hyper-0.9 which uses the previous version of the library.

Could I ask you to check with this new branch `with_hyper-0.9`? If it works with your environment, I'll release a new version based on the branch. If it doesn't work, I'd like you to try treasuredata_fdw 1.0.0 again.

Thanks for your patients.

**Comment by rotten** [comment]
No problem.
The build is failing.  I don't know enough about coding in Rust to troubleshoot it:

```
   Compiling unicode-bidi v0.3.4
error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/explicit.rs:180:32
    |
180 |         self.vec.push(Status { level, status });
    |                                ^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/explicit.rs:180:39
    |
180 |         self.vec.push(Status { level, status });
    |                                       ^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:226:13
    |
226 |             text,
    |             ^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:227:13
    |
227 |             original_classes,
    |             ^^^^^^^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:228:13
    |
228 |             paragraphs,
    |             ^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:303:13
    |
303 |             text,
    |             ^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:304:13
    |
304 |             original_classes,
    |             ^^^^^^^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:305:13
    |
305 |             paragraphs,
    |             ^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
   --> /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-bidi-0.3.4/src/lib.rs:306:13
    |
306 |             levels,
    |             ^^^^^^

error: aborting due to 9 previous errors

error: Could not compile `unicode-bidi`.
Build failed, waiting for other jobs to finish...
error: build failed
Makefile:19: recipe for target 'bridge_td_client_rust' failed
make: *** [bridge_td_client_rust] Error 101
```

**Comment by komamitsu** [comment]
Oh, your Rust is 1.16. Could you update Rust version?

If you installed Rust via `rustup`, execute this command (See also https://github.com/rust-lang-nursery/rustup.rs#keeping-rustup-up-to-date)
```
$ rustup self update
```

If not, reinstall Rust like this
```
### Uninstall the existing one if needed
$ sudo /usr/local/lib/rustlib/uninstall.sh

$ curl https://sh.rustup.rs -sSf | sh
```

Testing with Rust 1.16 might be related to this issue, I think. Can I ask you to try the current `master` branch again after update or re-install Rust? If it still fails, please try `with_hyper-0.9` branch.

**Comment by rotten** [comment]
I had been using the standard Ubuntu Rust package.   I uninstalled it, and then installed Rust as directed.

Went to the master branch and did a pull/make/make install. --> still crashes.

Then I tried the "with-hyper-0.9" branch.

That works. (!Yay!) I get rows back now instead of crashing the database.

Let me know if there is anything else you'd like me to try.

```
2017-07-26 13:03:50.730 EDT mydb [local] rick LOG:  connection authorized: user=rick database=mydb
2017-07-26 13:03:52.525 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, query=(null), import_file_size=134217728, atomic_import=0
2017-07-26 13:03:52.525 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.525 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, query=(null), import_file_size=134217728, atomic_import=0
2017-07-26 13:03:52.525 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.525 EDT mydb [local] rick DEBUG:  treasuredata_fdw: endpoint=(null), query_engine=presto, apikey.len=45, database=sample_datasets, table=www_access, query=(null), import_file_size=134217728, atomic_import=0
2017-07-26 13:03:52.525 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: entering
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: apikey.len=45
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: endpoint=None
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: query_engine="presto"
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: database="sample_datasets"
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: query="SELECT \"time\", host, path, referer, code, agent, size, method FROM www_access"
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.526 EDT mydb [local] rick DEBUG:  issue_query: domain_key=Uuid("xxx")
2017-07-26 13:03:52.526 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:03:52.528 EDT mydb [local] rick DEBUG:  issue_query: query_type=Presto
2017-07-26 13:03:52.528 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:04:02.858 EDT mydb [local] rick DEBUG:  issue_query: job finished. job_id=xxx
2017-07-26 13:04:02.858 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:04:02.858 EDT mydb [local] rick DEBUG:  issue_query: exiting
2017-07-26 13:04:02.858 EDT mydb [local] rick STATEMENT:  select * from public.sample_www_access;
2017-07-26 13:04:03.020 EDT mydb [local] rick LOG:  duration: 10497.169 ms  statement: select * from public.sample_www_access;

```

**Comment by komamitsu** [comment]
Glad to hear that 🎉 

And I noticed we may be able to know the root cause of this issue with RUST_BACKTRACE=1 w/o PostgreSQL.

I created a new repository that only creates a td-client-rust client that causes the crash . Could you try these commands when you get a chance?
```
$ git clone https://github.com/komamitsu/treasuredata_fdw_test.git
$ cd treasuredata_fdw_test
$ RUST_BACKTRACE=1 cargo run
```

**Comment by rotten** [comment]
```
    Finished dev [unoptimized + debuginfo] target(s) in 16.96 secs
     Running `target/debug/treasuredata_fdw_test`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:49
  10: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:21
  11: openssl::ssl::SslContextBuilder::set_options
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.15/src/ssl/mod.rs:640
  12: openssl::ssl::connector::ctx
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.15/src/ssl/connector.rs:40
  13: openssl::ssl::connector::SslConnectorBuilder::new
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.15/src/ssl/connector.rs:57
  14: native_tls::imp::TlsConnector::builder
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.1.4/src/imp/openssl.rs:183
  15: native_tls::TlsConnector::builder
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/native-tls-0.1.4/src/lib.rs:379
  16: hyper_native_tls::NativeTlsClient::new
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-native-tls-0.2.4/src/lib.rs:145
  17: <td_client::client::Client<td_client::client::DefaultRequestExecutor>>::new
             at /home/rotten/.cargo/registry/src/github.com-1ecc6299db9ec823/td-client-0.5.0/src/client.rs:94
  18: treasuredata_fdw_test::main
             at src/main.rs:12
  19: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  20: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  21: main
  22: __libc_start_main
  23: _start
```

**Comment by komamitsu** [comment]
Thanks. It seems a bug of rust-openssl. I'll look into it and report it when I have a time. I have only one question about that.
Could you tell me the result of `uname -a`?

BTW, I'll release a new version based on the `with-hyper-0.9` branch.

**Comment by rotten** [comment]
My laptop, where I've been doing this testing:

```
$ uname -a

Linux rick-laptop 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

fwiw:

```
$  cat /etc/os-release
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```


My production systems are Ubuntu 16.04.  I haven't tried the rust fdw there yet, since I backed out after the first attempt.  (Still using Multicorn)

```
$  uname -a
Linux core-gce 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by komamitsu** [comment]
@rotten I just released treasuredata_fdw 1.2.4 that uses Hyper 0.9 which worked on your laptop as `with-hyper-0.9` branch. You can use it with pulling `master` branch or `1.2.4` tag. I hope it works with your environments.

RE the result of `uname -a`, the openssl library's problem seemed to be related to the difference between 32 and 64bit architectures. So I guessed your laptop might be a 32bit machine. But it's a 64bit one. Unfortunately, it doesn't seem easy to find the cause of the openssl library's bug.

**Comment by komamitsu** [comment]
Closing this issue. If you still have any problem on this issue, feel free to reopen.
